Get http://localhost:3000/users
###
Get http://localhost:3000/users?take=4&skip=3
###
Get http://localhost:3000/users/1
###
DELETE http://localhost:3000/users/3
###
POST http://localhost:3000/users
Content-Type: application/json 
{
    "name":"oumaima madani cherif",
    "email": "oumaimamc@gmail.com",
    "password":"btsenset",
    "role":"ADMIN"
}
###
PATCH http://localhost:3000/users

Content-Type:
 {
"id":2,
 "name":"Salim Kardoud"

}